spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrent
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: carrent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: carrent

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
