spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrent
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: carrent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: carrent

